### PR TITLE
dashboard

### PR DESCRIPTION
**Pull request by kareraolivier**
Plz i would like your feedback

### CODE REVIEW

**Comment by kareraolivier** [comment]
feedback will be usefull

**Comment by BenIraa** [comment]
Resolve  Conflicts in those Files

**Comment by kareraolivier** [comment]
https://us04web.zoom.us/j/71144581811?pwd=tlZmagj2pMNX0TcjhKoAIyUKhZS4r2.1

**Review by un-anelka — COMMENTED** [review]
Work on the Hamburger Menu

**Pull request closed without merging**
